name: Runners

on:
  push:

defaults:
  run:
    working-directory: node-app

jobs:
  build:
    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}
    - run: npm ci
    - run: npm test